hmrc/binding-tariff-admin-frontend

app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala
DIT-1429: added BTI to file name
=> DIT-1429: added BTI to file name

anonymise.bat, anonymise.sh, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/filters/CustomFrontendFilters.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/views/case_migration_upload.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/components/form_button.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/components/json.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/data_migration_upload.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/file_migration_upload.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/monitor.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/password_expired.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/reset_confirm.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/scheduler.scala.html, conf/app.routes, conf/application.conf, project/AppDependencies.scala, test/it/uk/gov/hmrc/bindingtariffadminfrontend/AdminIntegrationTest.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonControllerSpec.scala
DIT-1804 : DEV: anonymousation of real data on production admin frontend (M)
=> DIT-1804 : DEV: anonymousation of real data on production admin frontend (M)

app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonControllerSpec.scala
DIT-1920: data comparison issues for JsArray
=> DIT-1920: data comparison issues for JsArray

app/assets/javascripts/data-processing.js, app/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataMigrationJsonConnector.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/views/csv_processing_status.scala.html, conf/app.routes, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataMigrationJsonConnectorSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonControllerSpec.scala
DIT-1530: changes for liabilities data migration json
=> DIT-1530: changes for liabilities data migration json

app/uk/gov/hmrc/bindingtariffadminfrontend/akka_fix/csv/CsvParser.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/akka_fix/csv/CsvParsing.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/akka_fix/csv/CsvParsingStage.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/akka_fix/csv/MalformedCsvException.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala, build.sbt, project/AppDependencies.scala
need to revert this once alpakka have fixed the CsvParser issue
=> alpakka_hack to fix linescanner

app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationUploadController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/FileMigrationUploadController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/filestore/UploadRequest.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/util/FilenameUtil.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/views/data_migration_upload.scala.html, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/connector/FileStoreConnectorTest.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationUploadControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/FileMigrationUploadControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/service/DataMigrationServiceTest.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/util/FilenameUtilTest.scala
=> DIT-2026 Enable txt files to be uploaded as migration data

app/uk/gov/hmrc/bindingtariffadminfrontend/model/classification/Event.scala
Related pull requests:
* https://github.com/hmrc/binding-tariff-data-transformation/pull/42
* https://github.com/hmrc/binding-tariff-classification/pull/133
=> DIT-1987 | Migrating completed liabilities with a new case completed event

app/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataMigrationJsonConnector.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationUploadController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/classification/Case.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/filestore/FileUploaded.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/views/data_migration_upload.scala.html, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataMigrationJsonConnectorSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonControllerSpec.scala
Also includes change to form to enter date of extract on csv to json conversion.
Requires other DIT-2137 PRs in Data Migration and backend.
=> Dit 2137 - added date of extract and migrated days elapsed fields.

app/uk/gov/hmrc/bindingtariffadminfrontend/model/classification/Event.scala
Supporting PR for https://github.com/hmrc/binding-tariff-data-transformation/pull/52
=> DIT-2108 | Added CaseCreated event so that it will be migrated

app/assets/javascripts/data-processing.js, app/uk/gov/hmrc/bindingtariffadminfrontend/views/csv_processing_status.scala.html
Depends upon https://github.com/hmrc/binding-tariff-data-transformation/pull/54
=> DIT-2109 | Present volumetrics during JSON creation

app/assets/javascripts/data-processing.js, app/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataMigrationJsonConnector.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/views/csv_processing_status.scala.html, conf/app.routes
Implements the front-end for downloading the report generated by the PR:
https://github.com/hmrc/binding-tariff-data-transformation/pull/57
=> DIT-2287 | Added a new button to download migration reports

app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/Anonymize.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/views/data_migration_upload.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/file_anonymisation_upload.scala.html, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/model/AnonymizeSpec.scala
Don't ask me why they called the file Legal_Proceedings 😆
=> DIT-2115 | Added Legal_Proceedings to the supported list of files for anonymization

app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/Anonymize.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/views/data_migration_upload.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/file_anonymisation_upload.scala.html, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/model/AnonymizeSpec.scala
Reverts hmrc/binding-tariff-admin-frontend#80 until we can merge https://github.com/hmrc/binding-tariff-data-transformation/pull/68
=> Revert "DIT-2115 | Added Legal_Proceedings to the supported list of files for anonymization"

app/uk/gov/hmrc/bindingtariffadminfrontend/model/classification/Event.scala
Supporting PR for https://github.com/hmrc/binding-tariff-data-transformation/pull/73
=> DIT-2117 | Added new event type "expert_advice_received"

app/assets/javascripts/historic-data-processing.js, app/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataMigrationJsonConnector.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationStateController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/HistoricDataUploadController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/Store.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/filestore/UploadRequest.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/service/DataMigrationService.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/views/historic_data_upload.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/historic_data_upload_status.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/index.scala.html, conf/app.routes, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataMigrationJsonConnectorSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/HistoricDataUploadControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/service/DataMigrationServiceTest.scala
This is ready for review, but should only be merged **after** https://github.com/hmrc/binding-tariff-data-transformation/pull/76
=> DIT 2436 | Added historic data upload

app/uk/gov/hmrc/bindingtariffadminfrontend/model/MigratedAttachment.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/classification/Attachment.scala
Supporting PR for https://github.com/hmrc/binding-tariff-data-transformation/pull/82
=> DIT-2121 | Added description to attachment model

app/uk/gov/hmrc/bindingtariffadminfrontend/service/DataMigrationService.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/service/DataMigrationServiceTest.scala
Attempting to use FileStore with a `FileSearch(ids = Some(Set()))` actually returns every attachment instead of no attachments, so these changes ensure we don't query FileStore if there are no uploads found.
=> DIT-2533 | Handle the case where there are no uploads found

app/assets/javascripts/historic-data-transformation.js, app/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataTransformationConnector.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationUploadController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/HistoricDataTransformationController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/HistoricDataUploadController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/transformation/HistoricTransformationStatistics.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/service/DataMigrationService.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/service/ResetService.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/views/historic_data_transformation.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/historic_data_transformation_status.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/index.scala.html, conf/app.routes, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataTransformationConnectorSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationUploadControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/HistoricDataTransformationControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/HistoricDataUploadControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/ResetControllerSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/service/DataMigrationServiceTest.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/service/ResetServiceTest.scala
Added pages to initiate/track/download transformed historic data.
Depends upon https://github.com/hmrc/binding-tariff-data-transformation/pull/91
=> DIT 2498 | Historic data transformation workflow

app/assets/javascripts/data-processing.js, app/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataTransformationConnector.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonController.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/classification/Application.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/views/csv_processing_status.scala.html, app/uk/gov/hmrc/bindingtariffadminfrontend/views/data_migration_upload.scala.html, conf/app.routes, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/connector/DataTransformationConnectorSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/controllers/DataMigrationJsonControllerSpec.scala
This is ready for review.
Also dependent upon https://github.com/hmrc/binding-tariff-data-transformation/pull/98
=> DIT-2322 | Support for transforming miscellaneous and correspondence cases

app/uk/gov/hmrc/bindingtariffadminfrontend/model/classification/Application.scala
To support https://github.com/hmrc/binding-tariff-data-transformation/pull/112
=> DIT-2575 | Updating liabilities application model

app/uk/gov/hmrc/bindingtariffadminfrontend/connector/BindingTariffClassificationConnector.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/model/ScheduledJob.scala, app/uk/gov/hmrc/bindingtariffadminfrontend/service/AdminMonitorService.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/connector/BindingTariffClassificationConnectorSpec.scala, test/unit/uk/gov/hmrc/bindingtariffadminfrontend/service/AdminMonitorServiceTest.scala
Allows running of https://github.com/hmrc/binding-tariff-classification/pull/167 manually for testing purposes
=> DIT-2430 | Added ability to run the fileStoreCleanup job
